CREATE TABLE Utilizador (
	ID VARCHAR(8) NOT NULL PRIMARY KEY,
	PrimeiroNome VARCHAR(16) NOT NULL,
	Apelido VARCHAR(16) NOT NULL,
	Email VARCHAR(16) NOT NULL,
	Senha VARCHAR(16) NOT NULL,
	Pa�s VARCHAR(16) NOT NULL,
	Nacionalidade VARCHAR(16) NOT NULL,
	DataDeNascimento VARCHAR(16) NOT NULL
);

CREATE TABLE Equipa (
	ID VARCHAR(8) NOT NULL PRIMARY KEY,
	Or�amento VARCHAR(16) NOT NULL,
	Nome VARCHAR(16) NOT NULL,
	Pontua��oTotal VARCHAR(16) NOT NULL,
	ID_utilizador VARCHAR(8) NOT NULL,

	FOREIGN KEY (ID_utilizador)
		REFERENCES Utilizador(ID)
);

CREATE TABLE Clube (
	ID VARCHAR(8) NOT NULL PRIMARY KEY,
	Nome VARCHAR(16) NOT NULL,
	Pa�s VARCHAR(16) NOT NULL,
);